version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.3
      docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-2)

      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
  build:
    commands:
      - php --version
      - docker build --tag 240778039237.dkr.ecr.us-east-2.amazonaws.com/cicd-demo:latest .
  post_build:
    commands:
      - docker push 240778039237.dkr.ecr.us-east-2.amazonaws.com/cicd-demo:latest
      - printf '[{"name":"hello-k8s","imageUri":"%s"}]' $TAG > build.json
artifacts:
  files: build.json
