version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.3
      docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --region ap-northeast-2 --no-include-email)

      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
  build:
    commands:
      - php --version
      - docker build --tag 240778039237.dkr.ecr.ap-northeast-2.amazonaws.com/cicd-ecr:latest .
  post_build:
    commands:
      - docker push 240778039237.dkr.ecr.ap-northeast-2.amazonaws.com/cicd-ecr:latest
      - printf $TAG > build.json
artifacts:
  files: build.json
